/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Billing;
import java.text.DecimalFormat;
import java.awt.print.*;
import java.awt.*;
import javax.swing.JOptionPane;

//import java.awt.event.*;
/**
 *
 * @author ComputationalMachine
 */
public class Bill extends javax.swing.JFrame implements Printable{

    /**
     * Creates new form Bill
     */
    private boolean customerSaved = false;
    private boolean materialOnly = false;
    private Customers aCustomer = new Customers();
    private Calculate calcs = new Calculate();
    private Bills aBill = new Bills();
    private DecimalFormat decf = new DecimalFormat("############0.00");
    private double laborFees, totDue, miscFees, prevBalance, materialTotal, tripCharge;
    //private final int TRIP_CHARGE = 48;
    private DBHandlers db = new DBHandlers();
    
    
    

    
    public Bill(Customers aCust, Bills aBill){
       // this.aBill = aBill;
       initComponents();
    }
    public Bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        timeField = new javax.swing.JTextField();
        laborChargeField = new javax.swing.JTextField();
        miscBox = new javax.swing.JTextField();
        tripField = new javax.swing.JTextField();
        tripBox = new javax.swing.JTextField();
        timeBox = new javax.swing.JTextField();
        laborBox = new javax.swing.JTextField();
        materialBox = new javax.swing.JTextField();
        materialField = new javax.swing.JTextField();
        miscField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        balanceField = new javax.swing.JTextField();
        dueField2 = new javax.swing.JTextField();
        serviceReportBox = new javax.swing.JTextField();
        timeBox1 = new javax.swing.JTextField();
        dosField = new javax.swing.JTextField();
        materialsUsedBox = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        materialArea = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        serviceArea = new javax.swing.JTextPane();
        printButton = new javax.swing.JButton();
        calcButton = new javax.swing.JButton();
        dueField1 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        propertyAddyField = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        balanceBox = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        mailField = new javax.swing.JTextField();
        cszField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        phoneField2 = new javax.swing.JTextField();
        billDateField = new javax.swing.JTextField();
        invoiceField = new javax.swing.JTextField();
        hoursField = new javax.swing.JTextField();
        minutesField = new javax.swing.JTextField();
        materialPrintButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setNextFocusableComponent(nameField);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Billing/clogo.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("8201 Sante Fe Dr. #181");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Littleton, CO 80120");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("(303) 973-1256");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Due upon receipt");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        timeField.setText("-");
        timeField.setBorder(null);
        timeField.setNextFocusableComponent(hoursField);
        timeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                timeFieldFocusGained(evt);
            }
        });
        timeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeFieldActionPerformed(evt);
            }
        });

        laborChargeField.setText("-");
        laborChargeField.setBorder(null);
        laborChargeField.setNextFocusableComponent(tripField);
        laborChargeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                laborChargeFieldFocusGained(evt);
            }
        });
        laborChargeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laborChargeFieldActionPerformed(evt);
            }
        });

        miscBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        miscBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        miscBox.setText("     Miscellaneous:");
        miscBox.setBorder(null);

        tripField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tripField.setText("48.00");
        tripField.setBorder(null);
        tripField.setNextFocusableComponent(materialField);
        tripField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tripFieldFocusGained(evt);
            }
        });

        tripBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tripBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tripBox.setText("Trip Charge:");
        tripBox.setBorder(null);

        timeBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        timeBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        timeBox.setText("Billed Hours:");
        timeBox.setBorder(null);
        timeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeBoxActionPerformed(evt);
            }
        });

        laborBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        laborBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        laborBox.setText("Labor Charge:");
        laborBox.setBorder(null);

        materialBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        materialBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        materialBox.setText("Materials:");
        materialBox.setBorder(null);

        materialField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        materialField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        materialField.setText("--");
        materialField.setBorder(null);
        materialField.setNextFocusableComponent(miscField);
        materialField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                materialFieldFocusGained(evt);
            }
        });

        miscField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        miscField.setText("-");
        miscField.setBorder(null);
        miscField.setNextFocusableComponent(balanceField);
        miscField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                miscFieldFocusGained(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 19)); // NOI18N
        jLabel10.setText("Bill Summary");

        balanceField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        balanceField.setText("-");
        balanceField.setBorder(null);
        balanceField.setNextFocusableComponent(dueField2);
        balanceField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                balanceFieldFocusGained(evt);
            }
        });

        dueField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dueField2.setText("-");
        dueField2.setBorder(null);
        dueField2.setNextFocusableComponent(serviceArea);
        dueField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dueField2FocusGained(evt);
            }
        });
        dueField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dueField2ActionPerformed(evt);
            }
        });

        serviceReportBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        serviceReportBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        serviceReportBox.setText("Service Report:");
        serviceReportBox.setBorder(null);

        timeBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        timeBox1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        timeBox1.setText("Date of Service:");
        timeBox1.setBorder(null);
        timeBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeBox1ActionPerformed(evt);
            }
        });

        dosField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dosField.setText("Date of Service:");
        dosField.setBorder(null);
        dosField.setNextFocusableComponent(timeField);
        dosField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dosFieldFocusGained(evt);
            }
        });
        dosField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosFieldActionPerformed(evt);
            }
        });

        materialsUsedBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        materialsUsedBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        materialsUsedBox.setText("Materials Used:");
        materialsUsedBox.setBorder(null);

        jScrollPane4.setBorder(null);

        materialArea.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        materialArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                materialAreaFocusGained(evt);
            }
        });
        jScrollPane4.setViewportView(materialArea);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);

        serviceArea.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        serviceArea.setNextFocusableComponent(materialArea);
        serviceArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                serviceAreaFocusGained(evt);
            }
        });
        jScrollPane3.setViewportView(serviceArea);

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        calcButton.setText("Calculate Bill");
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        dueField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dueField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dueField1.setText("Enter Amt. Due");
        dueField1.setBorder(null);
        dueField1.setNextFocusableComponent(billDateField);
        dueField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dueField1FocusGained(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setText("Amount Due:");
        jTextField1.setBorder(null);

        propertyAddyField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        propertyAddyField.setText("propertyAddress");
        propertyAddyField.setBorder(null);
        propertyAddyField.setNextFocusableComponent(phoneField);
        propertyAddyField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                propertyAddyFieldFocusGained(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText("Bill Date:");
        jTextField2.setBorder(null);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText("Invoice #:");
        jTextField3.setBorder(null);

        nameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameField.setText("CustomerName");
        nameField.setBorder(null);
        nameField.setNextFocusableComponent(mailField);
        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
        });

        balanceBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        balanceBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        balanceBox.setText("Previous Balance:");
        balanceBox.setBorder(null);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setText("Amount Due:");
        jTextField6.setBorder(null);

        mailField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mailField.setText("Mailing Address");
        mailField.setBorder(null);
        mailField.setNextFocusableComponent(cszField);
        mailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFieldFocusGained(evt);
            }
        });

        cszField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cszField.setText("City, State, Zip");
        cszField.setBorder(null);
        cszField.setNextFocusableComponent(propertyAddyField);
        cszField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cszFieldFocusGained(evt);
            }
        });

        phoneField.setText("Customer Phone Number");
        phoneField.setBorder(null);
        phoneField.setNextFocusableComponent(phoneField2);
        phoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFieldFocusGained(evt);
            }
        });

        phoneField2.setText("Alternate Customer Phone Number");
        phoneField2.setBorder(null);
        phoneField2.setNextFocusableComponent(invoiceField);
        phoneField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneField2FocusGained(evt);
            }
        });

        billDateField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        billDateField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        billDateField.setText("today's date...");
        billDateField.setBorder(null);
        billDateField.setNextFocusableComponent(dosField);
        billDateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                billDateFieldFocusGained(evt);
            }
        });

        invoiceField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        invoiceField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        invoiceField.setText("Enter Invoice #");
        invoiceField.setBorder(null);
        invoiceField.setNextFocusableComponent(dueField1);
        invoiceField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                invoiceFieldFocusGained(evt);
            }
        });

        hoursField.setText("hours");
        hoursField.setNextFocusableComponent(minutesField);
        hoursField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hoursFieldFocusGained(evt);
            }
        });

        minutesField.setText("minutes");
        minutesField.setNextFocusableComponent(laborChargeField);
        minutesField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                minutesFieldFocusGained(evt);
            }
        });

        materialPrintButton.setText("Print Materials Only");
        materialPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialPrintButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("include your email for Spring turn on and winterization notices");

        jLabel8.setText("__________________________________________________________");

        resetButton.setText("Reset Bill");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneField2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tripBox, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialBox, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laborBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hoursField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minutesField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(materialField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dosField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(laborChargeField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(193, 193, 193)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dueField2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tripField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(312, 312, 312))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(propertyAddyField, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                                .addComponent(cszField, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                                .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameField))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(billDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dueField1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(invoiceField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(miscBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(miscField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(serviceReportBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(materialsUsedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(printButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(calcButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(materialPrintButton)
                                    .addGap(28, 28, 28)
                                    .addComponent(resetButton)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(balanceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(balanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(phoneField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dueField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cszField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propertyAddyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(timeBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(timeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hoursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(minutesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(laborBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(laborChargeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tripBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tripField)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(materialBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(materialField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(miscBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(miscField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serviceReportBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(balanceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dueField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(materialsUsedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printButton)
                    .addComponent(calcButton)
                    .addComponent(materialPrintButton)
                    .addComponent(resetButton))
                .addGap(690, 690, 690))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dosFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosFieldActionPerformed

    private void timeBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeBox1ActionPerformed

    private void timeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeBoxActionPerformed

    private void timeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeFieldActionPerformed
 
    @Override
    public int print(Graphics g, PageFormat pf, int page) throws
                                                        PrinterException {

        if (page > 0) { 
            return NO_SUCH_PAGE;
        }
        Graphics2D g2d = (Graphics2D)g;
        g2d.translate(pf.getImageableX(), pf.getImageableY());
        if(materialOnly)
            materialArea.printAll(g);
        else
            jPanel1.printAll(g);
        return PAGE_EXISTS;
    }//end print
    
    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed

        if(propertyAddyField.getText().equals("propertyAddress") || propertyAddyField.getText().equals(" "))
            propertyAddyField.setVisible(false);
        else
            propertyAddyField.setText("RE: " + propertyAddyField.getText());
        if(timeField.getText().equals("") || timeField.getText().equals("-")){
            timeField.setVisible(false);
            timeBox.setVisible(false);
        }
        if(laborChargeField.getText().equals("") || laborChargeField.getText().equals("-")){
            laborChargeField.setVisible(false);
            laborBox.setVisible(false);
        }
        if(tripField.getText().equals("")){
            tripField.setVisible(false);
            tripBox.setVisible(false);
        }
         if(materialField.getText().equals("")|| materialField.getText().equals("-")){
            materialField.setVisible(false);
            materialBox.setVisible(false);
        }
         if(materialArea.getText().equals("")){
             materialsUsedBox.setVisible(false);
         }
        phoneField.setVisible(false);
        phoneField2.setVisible(false);   
        if(miscField.getText().equals("") || miscField.getText().equals("-") ){
        miscField.setVisible(false);
        miscBox.setVisible(false);
        }
        if(balanceField.getText().equals("") || balanceField.getText().equals("-") ){
            balanceField.setVisible(false);
            balanceBox.setVisible(false);
        }
        hoursField.setVisible(false);
        minutesField.setVisible(false);
        if(materialOnly){
            materialOnly = false;
            materialsUsedBox.setVisible(false);
            materialArea.setVisible(false);
            jScrollPane4.setVisible(false);
        }
        loadBillCust();
        /*print routine------------------------------------------------------------*/            
        PrinterJob pjp = PrinterJob.getPrinterJob();
        pjp.setPrintable(this);
        boolean ok = pjp.printDialog();
        if (ok) {
            try {
                pjp.print();
            }catch (PrinterException ex) {
               JOptionPane.showMessageDialog(null, "Some sort of printer error has occurred, try again or contact jason"); 
            }
        }//endif
    }//GEN-LAST:event_printButtonActionPerformed
    
    private void loadBillCust(){
        String datum[] = nameField.getText().split("\\s+");
        String[] cityState = cszField.getText().split("\\s+");  //Splits city, state & zip into seperate vars
        //split the contents of the name field into a seperate first and last name
        try{
            if(datum.length<2){
                aCustomer.setLastName(datum[0]);
            } else if(datum.length == 2) {
                aCustomer.setFirstName(datum[0]);
                aCustomer.setLastName(datum[1]);
            }else {
                aCustomer.setFirstName(datum[1]);
                aCustomer.setLastName(datum[2]);
            }
               if(!propertyAddyField.getText().equals("") || !propertyAddyField.getText().equals("propertyAddress")){
                aCustomer.setAddy(propertyAddyField.getText());
                aCustomer.setMailAddy(mailField.getText());
            }else{
                aCustomer.setAddy(mailField.getText());
                aCustomer.setMailAddy(mailField.getText());
            }
            // ternary to get rid of trailing commas (,) from state field
            aCustomer.setCity((cityState[0].charAt(cityState[0].length()-1)==',') ? cityState[0] = cityState[0].substring(0, cityState[0].length()-1) : cityState[0]);
            aCustomer.setState(cityState[1]);
            aCustomer.setZip(cityState[2]);
            aCustomer.setPhone(phoneField.getText());
            if(!phoneField2.equals("") && !phoneField2.equals("Alternate Customer Phone Number"))
               aCustomer.setPhone2(phoneField2.getText());
            /*------------------------------------Bill stuff--------------------------------*/
           aBill.setBillDate(billDateField.getText());
           aBill.setCustID(aCustomer.getCustID());
           aBill.setDateOfService(dosField.getText());
           aBill.setInvNum(invoiceField.getText());
           aBill.setTime(timeField.getText());
           aBill.setMisc(miscFees);
           aBill.setServiceReport(serviceArea.getText());
           aBill.setMaterialString(materialArea.getText());
           aBill.setLabor(laborFees);
           aBill.setMaterialsTotal(materialTotal);
           aBill.setTotal(totDue);
           aBill.setTripCharge(tripCharge);
           aBill.setTripFee(true);//???????????????????????????????????
        }catch(NullPointerException e){
            e.printStackTrace();
        }
        db.query(aCustomer, aBill);
      
    }//loadBillCust
    
    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        int minutes = 0;
        int hours = 0;
        
        invoiceField.setText(calcs.generateID());
        billDateField.setText(calcs.getDate());
        try{
            tripCharge = Double.parseDouble(tripField.getText());
        }catch(NumberFormatException e){
            tripCharge = 0;
        }
        if(!miscField.getText().equals("") && !miscField.getText().equals("-") ){
           miscFees = Double.parseDouble(miscField.getText());
        }else{
            miscFees =  0;
        }
        if(!balanceField.getText().equals("") && !balanceField.getText().equals("-") ){
            prevBalance = Double.parseDouble(balanceField.getText());
        }else{
            prevBalance =  0;
        }
        materialTotal = calcs.totalMaterials(materialArea.getText()); 
        materialField.setText(decf.format(materialTotal));
        if(minutesField.getText() != null && Character.isDigit(minutesField.getText().charAt(0))){
           minutes = !minutesField.equals("minutes") ? Integer.parseInt(minutesField.getText()) : 0;
        }
      /*******************************************************?*/
        if(hoursField.getText() != null && Character.isDigit(hoursField.getText().charAt(0)))
           hours = Integer.parseInt(hoursField.getText());
           
           timeField.setText(hours + " hour(s) " + minutes + " min.");
           if (dosField.getText().equals("Date of Service:"))
               dosField.setText(" ");
           laborFees = calcs.calcLabor(hours, minutes);
           laborChargeField.setText(decf.format(laborFees));
           totDue = (calcs.calcTotal(materialTotal, laborFees, tripCharge, miscFees, prevBalance));
           dueField1.setText(decf.format(totDue));
           dueField2.setText(decf.format(totDue));
           loadBillCust();

            
            
        
    }//GEN-LAST:event_calcButtonActionPerformed

    private void laborChargeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laborChargeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laborChargeFieldActionPerformed

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusGained
        nameField.selectAll();                  
    }//GEN-LAST:event_nameFieldFocusGained

    private void hoursFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hoursFieldFocusGained
        hoursField.selectAll();
    }//GEN-LAST:event_hoursFieldFocusGained

    private void mailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFieldFocusGained
        mailField.selectAll();
    }//GEN-LAST:event_mailFieldFocusGained

    private void cszFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cszFieldFocusGained
        cszField.selectAll();
    }//GEN-LAST:event_cszFieldFocusGained

    private void propertyAddyFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_propertyAddyFieldFocusGained
        propertyAddyField.selectAll();
    }//GEN-LAST:event_propertyAddyFieldFocusGained

    private void invoiceFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_invoiceFieldFocusGained
        invoiceField.selectAll();
    }//GEN-LAST:event_invoiceFieldFocusGained

    private void dueField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dueField1FocusGained
        dueField1.selectAll();
    }//GEN-LAST:event_dueField1FocusGained

    private void billDateFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_billDateFieldFocusGained
        billDateField.selectAll();
    }//GEN-LAST:event_billDateFieldFocusGained

    private void timeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_timeFieldFocusGained
        timeField.selectAll();
    }//GEN-LAST:event_timeFieldFocusGained

    private void dosFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dosFieldFocusGained
        dosField.selectAll();
    }//GEN-LAST:event_dosFieldFocusGained

    private void minutesFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_minutesFieldFocusGained
        minutesField.selectAll();
    }//GEN-LAST:event_minutesFieldFocusGained

    private void laborChargeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_laborChargeFieldFocusGained
        laborChargeField.selectAll();
    }//GEN-LAST:event_laborChargeFieldFocusGained

    private void tripFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tripFieldFocusGained
          tripField.selectAll();
    }//GEN-LAST:event_tripFieldFocusGained

    private void materialFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_materialFieldFocusGained
        materialField.selectAll();
    }//GEN-LAST:event_materialFieldFocusGained

    private void miscFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_miscFieldFocusGained
        miscField.selectAll();        // TODO add your handling code here:
    }//GEN-LAST:event_miscFieldFocusGained

    private void balanceFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_balanceFieldFocusGained
        balanceField.selectAll();        // TODO add your handling code here:
    }//GEN-LAST:event_balanceFieldFocusGained

    private void dueField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dueField2FocusGained
        dueField2.selectAll();
    }//GEN-LAST:event_dueField2FocusGained

    private void serviceAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_serviceAreaFocusGained
        serviceArea.selectAll();
    }//GEN-LAST:event_serviceAreaFocusGained

    private void phoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFieldFocusGained
            phoneField.selectAll();        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldFocusGained

    private void phoneField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneField2FocusGained
        phoneField2.selectAll();
    }//GEN-LAST:event_phoneField2FocusGained

    private void materialAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_materialAreaFocusGained
        materialArea.selectAll();
    }//GEN-LAST:event_materialAreaFocusGained

    private void dueField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dueField2ActionPerformed

    private void materialPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialPrintButtonActionPerformed
        materialOnly = true;
        try{
        materialArea.print();
        }catch (PrinterException e){
            
        }System.out.println(materialOnly + "= mat only");
    }//GEN-LAST:event_materialPrintButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        propertyAddyField.setVisible(true);
       
        timeField.setVisible(true);
        timeBox.setVisible(true);
            laborChargeField.setVisible(true);
            laborBox.setVisible(true);
            tripField.setVisible(true);
            tripBox.setVisible(true);
            materialField.setVisible(true);
            materialBox.setVisible(true);
             materialsUsedBox.setVisible(true);
       
        phoneField.setVisible(true);
        phoneField2.setVisible(true);   
        miscField.setVisible(true);
        miscBox.setVisible(true);
            balanceField.setVisible(true);
            balanceBox.setVisible(true);
        hoursField.setVisible(true);
        minutesField.setVisible(true);
            materialOnly = true;
            materialsUsedBox.setVisible(true);
            materialArea.setVisible(true);
            jScrollPane4.setVisible(true);
            dosField.setText("");
            timeField.setText("");
            dueField1.setText("");
            dueField2.setText("");
            laborChargeField.setText("");
            invoiceField.setText("");
            billDateField.setText("");
            tripField.setText("");
            
            materialField.setText("");
            
             nameField.setText("CustomerName");
       mailField.setText("Mailing Address");
       cszField.setText("City, State, Zip");
       propertyAddyField.setText("propertyAddress");
        phoneField.setText("");
        phoneField2.setText("");   
        miscField.setText("");
        
            balanceField.setText("");
          
        hoursField.setText("");
        minutesField.setText("");
            materialOnly = false;
           
            materialArea.setText("");
            
    }//GEN-LAST:event_resetButtonActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balanceBox;
    private javax.swing.JTextField balanceField;
    private javax.swing.JTextField billDateField;
    private javax.swing.JButton calcButton;
    private javax.swing.JTextField cszField;
    private javax.swing.JTextField dosField;
    private javax.swing.JTextField dueField1;
    private javax.swing.JTextField dueField2;
    private javax.swing.JTextField hoursField;
    private javax.swing.JTextField invoiceField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField laborBox;
    private javax.swing.JTextField laborChargeField;
    private javax.swing.JTextField mailField;
    private javax.swing.JTextPane materialArea;
    private javax.swing.JTextField materialBox;
    private javax.swing.JTextField materialField;
    private javax.swing.JButton materialPrintButton;
    private javax.swing.JTextField materialsUsedBox;
    private javax.swing.JTextField minutesField;
    private javax.swing.JTextField miscBox;
    private javax.swing.JTextField miscField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField phoneField2;
    private javax.swing.JButton printButton;
    private javax.swing.JTextField propertyAddyField;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextPane serviceArea;
    private javax.swing.JTextField serviceReportBox;
    private javax.swing.JTextField timeBox;
    private javax.swing.JTextField timeBox1;
    private javax.swing.JTextField timeField;
    private javax.swing.JTextField tripBox;
    private javax.swing.JTextField tripField;
    // End of variables declaration//GEN-END:variables
}
